apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ox-app.fullname" . }}
  labels:
    {{- include "ox-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ox-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ox-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: {{ .Values.command | toYaml | nindent 12 }}
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ox-app-redis
                key: redis-password
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}